import { MouseInputModule } from './MouseInputModule';
import { Pointer } from './Pointer';
import { Region } from './Region';
import { TouchInputModule } from './TouchInputModule';
import { Vector2 } from './Vector2';
declare class InputController {
    __binded_on_mousedown: any;
    __binded_on_mouseleave: any;
    __binded_on_mousemove: any;
    __binded_on_mouseup: any;
    __binded_on_touchcancel: any;
    __binded_on_touchend: any;
    __binded_on_touchmove: any;
    __binded_on_touchstart: any;
    __binded_on_wheel: any;
    active_input_module: MouseInputModule | TouchInputModule;
    dom_element: HTMLElement;
    mouse_input_module: MouseInputModule;
    region: Region;
    sub_region_element: HTMLElement;
    touch_cooldown: Date;
    touch_input_module: TouchInputModule;
    init(dom_element: HTMLElement, sub_region_element?: HTMLElement | undefined): void;
    bind_events(): void;
    unbind_events(): void;
    on_wheel(event: WheelEvent): void;
    on_touchstart(event: TouchEvent): void;
    on_touchmove(event: TouchEvent): void;
    on_touchcancel(event: TouchEvent): void;
    on_touchend(event: TouchEvent): void;
    on_mousedown(event: MouseEvent): void;
    on_mousemove(event: MouseEvent): void;
    on_mouseup(event: MouseEvent): void;
    on_mouseleave(event: MouseEvent): void;
    clear(): void;
    mouse_input_allowed(): boolean;
    set_mouse_input_active(): void;
    set_touch_input_active(): void;
    get left_mouse_button_pressed(): boolean;
    get left_mouse_button_down(): boolean;
    get left_mouse_button_released(): boolean;
    get right_mouse_button_pressed(): boolean;
    get right_mouse_button_down(): boolean;
    get right_mouse_button_released(): boolean;
    get middle_mouse_button_pressed(): boolean;
    get middle_mouse_button_down(): boolean;
    get middle_mouse_button_released(): boolean;
    get is_touchscreen(): boolean;
    get scroll_delta(): number;
    get zoom_delta(): number;
    get pointer_count(): number;
    get pointer_is_within_bounds(): boolean;
    pointer_is_over_element(elem: HTMLElement): boolean;
    get pointers(): Pointer[];
    get pointer_pos(): Vector2;
    get pointer_pos_delta(): Vector2;
    get NDC(): Vector2;
    get NDC_delta(): Vector2;
    get pointer_center(): Vector2;
    get pointer_center_delta(): Vector2;
    get pointer_center_NDC(): Vector2;
    get pointer_center_NDC_delta(): Vector2;
    get_pointer_pos(index?: number): Vector2;
    get_pointer_pos_delta(index?: number): Vector2;
    get_pointer_NDC(index?: number): Vector2;
    get_pointer_NDC_delta(index?: number): Vector2;
    dispose(): void;
}
export { InputController };
