declare class InputController {
    __binded_on_mousedown: any;
    __binded_on_mouseleave: any;
    __binded_on_mousemove: any;
    __binded_on_mouseup: any;
    __binded_on_touchcancel: any;
    __binded_on_touchend: any;
    __binded_on_touchmove: any;
    __binded_on_touchstart: any;
    __binded_on_wheel: any;
    active_input_module: any;
    dom_element: any;
    mouse_input_module: any;
    region: any;
    sub_region_element: any;
    touch_cooldown: any;
    touch_input_module: any;
    init(dom_element: any, sub_region_element: any): void;
    bind_events(): void;
    unbind_events(): void;
    on_wheel(event: any): void;
    on_touchstart(event: any): void;
    on_touchmove(event: any): void;
    on_touchcancel(event: any): void;
    on_touchend(event: any): void;
    on_mousedown(event: any): void;
    on_mousemove(event: any): void;
    on_mouseup(event: any): void;
    on_mouseleave(event: any): void;
    clear(): void;
    mouse_input_allowed(): boolean;
    set_mouse_input_active(): void;
    set_touch_input_active(): void;
    get left_mouse_button_pressed(): any;
    get left_mouse_button_down(): any;
    get left_mouse_button_released(): any;
    get right_mouse_button_pressed(): any;
    get right_mouse_button_down(): any;
    get right_mouse_button_released(): any;
    get middle_mouse_button_pressed(): any;
    get middle_mouse_button_down(): any;
    get middle_mouse_button_released(): any;
    get is_touchscreen(): any;
    get scroll_delta(): any;
    get zoom_delta(): any;
    get pointer_count(): any;
    get pointer_is_within_bounds(): boolean;
    pointer_is_over_element(elem: any): boolean;
    get pointers(): any;
    get pointer_pos(): any;
    get pointer_pos_delta(): any;
    get NDC(): any;
    get NDC_delta(): any;
    get pointer_center(): any;
    get pointer_center_delta(): any;
    get pointer_center_NDC(): any;
    get pointer_center_NDC_delta(): any;
    get_pointer_pos(index?: number): any;
    get_pointer_pos_delta(index?: number): any;
    get_pointer_NDC(index?: number): any;
    get_pointer_NDC_delta(index?: number): any;
    dispose(): void;
}
export { InputController };
