import { Pointer } from './Pointer';
import type { Region } from './Region';
import { Vector2 } from './Vector2';
declare class TouchInputModule {
    default_pointer: Pointer;
    left_mouse_button_down: boolean;
    left_mouse_button_pressed: boolean;
    left_mouse_button_released: boolean;
    pointers: Pointer[];
    previous_primary_pointer_pos: Vector2;
    previous_separation_distance: number | undefined;
    region: Region;
    zoom_delta: number;
    constructor(region: Region);
    get_pointer(i: number): Pointer;
    get is_touchscreen(): boolean;
    get scroll_delta(): number;
    get_primary_pointer(): Pointer;
    get pointer_pos_delta(): Vector2;
    get pointer_count(): number;
    get pointer_center(): Vector2;
    get previous_pointer_center(): Vector2;
    get pointer_center_NDC(): Vector2;
    get previous_pointer_center_NDC(): Vector2;
    get pointer_center_delta(): Vector2;
    get pointer_center_NDC_delta(): Vector2;
    update_pointer_separation(): void;
    pointers_moving_away_from_each_other(): boolean;
    update_pointer(pointer_id: any, x: any, y: any): Pointer;
    remove_pointer(pointer_id: any): void;
    is_primary_pointer(pointer: any): boolean;
    pointer_down(event: TouchEvent): void;
    pointer_up(event: TouchEvent): void;
    pointer_move(event: TouchEvent): void;
    pointer_cancel(event: TouchEvent): void;
    pointer_out(event: TouchEvent): void;
    clear(): void;
}
export { TouchInputModule };
